USE PROGWEB;

CREATE TABLE LIVRO(
	IDLIV_LIV INT NOT NULL AUTO_INCREMENT,
    TITUL_LIV VARCHAR(100) NOT NULL UNIQUE,
    AUTOR_LIV VARCHAR(100),
    STLEI_LIV CHAR(1) NOT NULL,
    DTLEI_LIV DATETIME,
    EMPRE_LIV VARCHAR(100),    
    SINOP_LIV VARCHAR(4000),    
    PRIMARY KEY (IDLIV_LIV)
);

CREATE TABLE TAG(
	IDTAG_TAG INT NOT NULL AUTO_INCREMENT,
    DESCR_TAG VARCHAR(20) NOT NULL,
    IDLIV_TAG INT NOT NULL,
    PRIMARY KEY (IDTAG_TAG),
    FOREIGN KEY (IDLIV_TAG) REFERENCES LIVRO(IDLIV_LIV)
);
