DELIMITER $$
CREATE PROCEDURE SP_CADASTRAR (
	IN TITUL VARCHAR(100),
    IN AUTOR VARCHAR(100),
    IN STLEI CHAR(1),
    IN DTLEI DATETIME,
    IN EMPRE VARCHAR(100),    
    IN SINOP VARCHAR(4000), 
    IN LISTA_TAG VARCHAR(200)
) BEGIN

	DECLARE TAM TINYINT UNSIGNED DEFAULT 0;
	DECLARE CONT TINYINT UNSIGNED DEFAULT 1; 
    SET TAM = ROUND ((LENGTH(LISTA_TAG)-LENGTH(REPLACE(LISTA_TAG, ",", "")))/LENGTH(","));

	INSERT INTO LIVRO VALUES (NULL, TITUL, AUTOR, STLEI, DTLEI, EMPRE, SINOP);    
          
    WHILE CONT < TAM + 1 AND LISTA_TAG <> "" DO    
		INSERT INTO TAG VALUES (NULL, SPLIT_STR(LISTA_TAG, ",", CONT), @@identity);
	END WHILE;
    
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE SP_EDITAR (
	IN IDLIV INT,
	IN TITUL VARCHAR(100),
    IN AUTOR VARCHAR(100),
    IN STLEI CHAR(1),
    IN DTLEI DATETIME,
    IN EMPRE VARCHAR(100),    
    IN SINOP VARCHAR(4000),  
    IN LISTA_TAG VARCHAR(200)
) BEGIN

	DECLARE TAM TINYINT UNSIGNED DEFAULT 0;
	DECLARE CONT TINYINT UNSIGNED DEFAULT 1; 
    SET TAM = ROUND ((LENGTH(LISTA_TAG)-LENGTH(REPLACE(LISTA_TAG, ",", "")))/LENGTH(","));
    
    DELETE FROM TAG WHERE IDLIV_TAG = IDLIV;
    WHILE CONT < TAM + 1 AND LISTA_TAG <> "" DO    
		INSERT INTO TAG VALUES (NULL, SPLIT_STR(LISTA_TAG, ",", CONT), IDLIV);
	END WHILE;
    
    UPDATE LIVRO SET 
		TITUL_LIV = TITUL, 
        AUTOR_LIV = AUTOR, 
        STLEI_LIV = STLEI, 
        DTLEI_LIV = DTLEI, 
        EMPRE_LIV = EMPRE, 
        SINOP_LIV = SINOP
	WHERE IDLIV_LIV = IDLIV;

END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE SP_EXCLUIR (
	IN  IDLIV INT
) BEGIN

	DELETE FROM TAG WHERE IDLIV_TAG = IDLIV;
	DELETE FROM LIVRO WHERE IDLIV_LIV = IDLIV;   
    
END $$
DELIMITER ;

    